services:
  database:
    image: postgres:16.4
    container_name: ctn_database
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - 3000:3000

#   frontend:

  backend:
    build:
      context: ./backend
    container_name: ctn_backend
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://db_user:db_pass@ctn_database/db_name
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000

#   redis:
#   sidekiq:

volumes:
  data:
