source 'http://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'redis'
gem 'sidekiq'

gem 'rackup'
gem 'rack'
gem 'rack-cors'

gem 'pg'
gem 'csv'
gem 'json'

gem 'byebug'
gem 'simplecov'
gem 'rubocop'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
end
